{{- if .Values.thanos.objstoreSecret.external }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "helios.fullname" . }}-thanos-objstore
  namespace: helios-storage
  labels:
    {{- include "helios.labels" . | nindent 4 }}
    app.kubernetes.io/component: thanos
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.thanos.objstoreSecret.storeRef | default "cluster-secret-store" }}
    kind: ClusterSecretStore
  target:
    name: {{ include "helios.fullname" . }}-thanos-objstore
    creationPolicy: Owner
  data:
    - secretKey: objstore.yml
      remoteRef:
        key: {{ .Values.thanos.objstoreSecret.remoteKey | default "helios/thanos-objstore" }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helios.fullname" . }}-thanos-objstore
  namespace: helios-storage
  labels:
    {{- include "helios.labels" . | nindent 4 }}
    app.kubernetes.io/component: thanos
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: {{ .Values.thanos.objstoreSecret.bucket | default "thanos" }}
      endpoint: {{ .Values.thanos.objstoreSecret.endpoint | default "minio.helios-storage.svc.cluster.local:9000" }}
      access_key: {{ .Values.thanos.objstoreSecret.accessKey | default "" }}
      secret_key: {{ .Values.thanos.objstoreSecret.secretKey | default "" }}
      insecure: {{ .Values.thanos.objstoreSecret.insecure | default true }}
{{- end }}
