goflow2:
  replicas: 2
  image:
    repository: netsampler/goflow2
    tag: v3.4.5
    pullPolicy: IfNotPresent
  udpPorts:
    - 2055
    - 6343
  kafkaTopic: helios-flows-raw

kafka:
  brokers: 3
  topics:
    - name: helios-flows-raw
      partitions: 24
      replicationFactor: 3
    - name: helios-flows-enriched
      partitions: 24
      replicationFactor: 3

flowEnricher:
  replicas: 2
  image:
    repository: ghcr.io/rhwendt/helios/flow-enricher
    tag: v0.1.0
    pullPolicy: IfNotPresent
  kafka:
    consumer:
      groupId: flow-enricher
      topic: helios-flows-raw
    producer:
      topic: helios-flows-enriched

clickhouseClient:
  image:
    repository: clickhouse/clickhouse-client
    tag: "24.1"
    pullPolicy: IfNotPresent

clickhouse:
  shards: 2
  replicas: 2
  storage: 100Gi
  # Set a password hash for the default user. In production, use ESO to manage this secret.
  defaultPasswordSha256: ""
