apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-flow-enricher
  labels:
    app.kubernetes.io/name: flow-enricher
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: flows
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-flow-enricher
  minReplicas: {{ .Values.flowEnricher.replicas }}
  maxReplicas: {{ mul .Values.flowEnricher.replicas 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
