apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: helios-visualization
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: datasources
    app.kubernetes.io/part-of: helios
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Thanos
        type: prometheus
        access: proxy
        url: http://thanos-query.helios-storage.svc.cluster.local:9090
        isDefault: true
        editable: false
        jsonData:
          httpMethod: POST
          timeInterval: 30s
      - name: Alertmanager
        type: alertmanager
        access: proxy
        url: http://alertmanager.helios-visualization.svc.cluster.local:9093
        editable: false
        jsonData:
          implementation: prometheus
      - name: ClickHouse
        type: grafana-clickhouse-datasource
        access: proxy
        url: http://clickhouse.helios-flows.svc.cluster.local:8123
        editable: false
        jsonData:
          defaultDatabase: helios_flows
