apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-snmp-exporter
  labels:
    app.kubernetes.io/name: snmp-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: collection
    app.kubernetes.io/part-of: helios
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: snmp-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: snmp
      interval: 60s
