apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-gnmic
  labels:
    app.kubernetes.io/name: gnmic
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: collection
    app.kubernetes.io/part-of: helios
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gnmic
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: gnmic_(.+)
          targetLabel: __name__
          replacement: gnmic_$1
        - sourceLabels: [source]
          targetLabel: device
        - sourceLabels: [subscription_name]
          targetLabel: subscription
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
