apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-target-generator
  labels:
    app.kubernetes.io/name: target-generator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: integration
---
{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-target-generator
  namespace: helios-collection
  labels:
    app.kubernetes.io/name: target-generator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: integration
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-target-generator
  namespace: helios-collection
  labels:
    app.kubernetes.io/name: target-generator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-target-generator
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-target-generator
    namespace: {{ .Release.Namespace }}
{{- end }}
